services:
  boxer:
    image: theonekeyg/boxer
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - boxer-data:/root/.boxer
      - ./docker/config.json:/etc/boxer/config.json:ro
    environment:
      - BOXER_CONFIG=/etc/boxer/config.json
    restart: unless-stopped

volumes:
  boxer-data:
