// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files": {
            "get": {
                "description": "Download any file by its relative path. To retrieve output files written by a container to /output/, use the path pattern output/\u003cexec_id\u003e/\u003cfilename\u003e.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Download a file from the file store",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative file path (e.g. output/boxer-abc123/result.json)",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File contents"
                    },
                    "400": {
                        "description": "Missing or invalid path",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Multipart upload. The stored file can be referenced by its path in POST /run — it is bind-mounted read-only at /\u003cpath\u003e inside the container.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload a file to the file store",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File content",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Relative destination path (e.g. workspace/script.py)",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stored path",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or invalid form fields",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Upload exceeds configured limit",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns {\"ok\": true} when the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/run": {
            "post": {
                "description": "Pulls the image if not cached, constructs a hardened OCI bundle, and runs the command inside a gVisor sandbox.\nFiles listed in ` + "`" + `files` + "`" + ` must be uploaded first via POST /files; each is bind-mounted read-only at /\u003cpath\u003e inside the container.\nOutput files written to /output/ inside the container are captured and retrievable via GET /files?path=output/\u003cexec_id\u003e/\u003cfilename\u003e.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execution"
                ],
                "summary": "Execute a command in a sandboxed container",
                "parameters": [
                    {
                        "description": "Execution parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Command completed (any exit code is valid — check exit_code)",
                        "schema": {
                            "$ref": "#/definitions/api.RunResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or file not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Wall-clock timeout exceeded",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error (image pull failed, runsc error)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "507": {
                        "description": "stdout or stderr exceeded the configured output limit",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "image pull failed: not found"
                }
            }
        },
        "api.RunRequest": {
            "type": "object",
            "required": [
                "cmd",
                "image"
            ],
            "properties": {
                "cmd": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "python3",
                        "-c",
                        "print('hello world')"
                    ]
                },
                "cwd": {
                    "type": "string",
                    "example": "/app"
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "HOME=/root",
                        "PYTHONPATH=/app"
                    ]
                },
                "files": {
                    "description": "Files lists relative paths of files previously uploaded via POST /files.\nEach file is bind-mounted read-only at /\u003cpath\u003e inside the container.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "workspace/script.py",
                        "workspace/data.json"
                    ]
                },
                "image": {
                    "type": "string",
                    "example": "python:3.12-slim"
                },
                "limits": {
                    "$ref": "#/definitions/config.ResourceLimits"
                },
                "network": {
                    "description": "Network sets the container network mode: none (default, no access),\nsandbox (isolated NAT namespace), or host (shared host network).",
                    "type": "string",
                    "default": "none",
                    "enum": [
                        "none",
                        "sandbox",
                        "host"
                    ],
                    "example": "none"
                },
                "persist": {
                    "description": "Persist keeps uploaded input files and captured output files after the run.\nDefault false: all files are deleted once the response is returned.",
                    "type": "boolean"
                }
            }
        },
        "api.RunResponse": {
            "type": "object",
            "properties": {
                "exec_id": {
                    "type": "string",
                    "example": "boxer-abc123"
                },
                "exit_code": {
                    "type": "integer",
                    "example": 0
                },
                "stderr": {
                    "type": "string",
                    "example": ""
                },
                "stdout": {
                    "type": "string",
                    "example": "hello world\n"
                },
                "wall_ms": {
                    "type": "integer",
                    "example": 342
                }
            }
        },
        "config.ResourceLimits": {
            "type": "object",
            "properties": {
                "cpu_cores": {
                    "type": "number"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "nofile": {
                    "type": "integer"
                },
                "pids_limit": {
                    "type": "integer"
                },
                "wall_clock_secs": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Boxer API",
	Description:      "Sandbox execution service: pull any container image, run arbitrary commands inside gVisor.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
