// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ImageCacher is an autogenerated mock type for the ImageCacher type
type ImageCacher struct {
	mock.Mock
}

type ImageCacher_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageCacher) EXPECT() *ImageCacher_Expecter {
	return &ImageCacher_Expecter{mock: &_m.Mock}
}

// Rootfs provides a mock function with given fields: ctx, imageRef
func (_m *ImageCacher) Rootfs(ctx context.Context, imageRef string) (string, error) {
	ret := _m.Called(ctx, imageRef)

	if len(ret) == 0 {
		panic("no return value specified for Rootfs")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, imageRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, imageRef)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, imageRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageCacher_Rootfs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rootfs'
type ImageCacher_Rootfs_Call struct {
	*mock.Call
}

// Rootfs is a helper method to define mock.On call
//   - ctx context.Context
//   - imageRef string
func (_e *ImageCacher_Expecter) Rootfs(ctx interface{}, imageRef interface{}) *ImageCacher_Rootfs_Call {
	return &ImageCacher_Rootfs_Call{Call: _e.mock.On("Rootfs", ctx, imageRef)}
}

func (_c *ImageCacher_Rootfs_Call) Run(run func(ctx context.Context, imageRef string)) *ImageCacher_Rootfs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ImageCacher_Rootfs_Call) Return(_a0 string, _a1 error) *ImageCacher_Rootfs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageCacher_Rootfs_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ImageCacher_Rootfs_Call {
	_c.Call.Return(run)
	return _c
}

// NewImageCacher creates a new instance of ImageCacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageCacher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageCacher {
	mock := &ImageCacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
