// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	config "boxer/config"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sandbox "boxer/sandbox"
)

// SandboxExecutor is an autogenerated mock type for the SandboxExecutor type
type SandboxExecutor struct {
	mock.Mock
}

type SandboxExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *SandboxExecutor) EXPECT() *SandboxExecutor_Expecter {
	return &SandboxExecutor_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, bundle, limits
func (_m *SandboxExecutor) Run(ctx context.Context, bundle *sandbox.BundleDir, limits config.ResourceLimits) (*sandbox.Result, error) {
	ret := _m.Called(ctx, bundle, limits)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *sandbox.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sandbox.BundleDir, config.ResourceLimits) (*sandbox.Result, error)); ok {
		return rf(ctx, bundle, limits)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sandbox.BundleDir, config.ResourceLimits) *sandbox.Result); ok {
		r0 = rf(ctx, bundle, limits)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sandbox.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sandbox.BundleDir, config.ResourceLimits) error); ok {
		r1 = rf(ctx, bundle, limits)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SandboxExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type SandboxExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - bundle *sandbox.BundleDir
//   - limits config.ResourceLimits
func (_e *SandboxExecutor_Expecter) Run(ctx interface{}, bundle interface{}, limits interface{}) *SandboxExecutor_Run_Call {
	return &SandboxExecutor_Run_Call{Call: _e.mock.On("Run", ctx, bundle, limits)}
}

func (_c *SandboxExecutor_Run_Call) Run(run func(ctx context.Context, bundle *sandbox.BundleDir, limits config.ResourceLimits)) *SandboxExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sandbox.BundleDir), args[2].(config.ResourceLimits))
	})
	return _c
}

func (_c *SandboxExecutor_Run_Call) Return(_a0 *sandbox.Result, _a1 error) *SandboxExecutor_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SandboxExecutor_Run_Call) RunAndReturn(run func(context.Context, *sandbox.BundleDir, config.ResourceLimits) (*sandbox.Result, error)) *SandboxExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewSandboxExecutor creates a new instance of SandboxExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSandboxExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *SandboxExecutor {
	mock := &SandboxExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
