// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns {\"ok\": true} when the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/run": {
            "post": {
                "description": "Pulls the image if not cached, then runs the command inside a\ngVisor sandbox. Returns stdout, stderr, exit code, and wall time.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execution"
                ],
                "summary": "Execute a command in a sandboxed container",
                "parameters": [
                    {
                        "description": "Execution parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Command completed (any exit code)",
                        "schema": {
                            "$ref": "#/definitions/api.RunResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Wall-clock timeout exceeded",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error (pull failed, runsc error)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "507": {
                        "description": "Output exceeded limit",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "image pull failed: not found"
                }
            }
        },
        "api.RunRequest": {
            "type": "object",
            "required": [
                "cmd",
                "image"
            ],
            "properties": {
                "cmd": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "python -c 'print(\"hello world\")'"
                    ]
                },
                "cwd": {
                    "type": "string",
                    "example": "/app"
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "HOME=/root"
                    ]
                },
                "image": {
                    "type": "string",
                    "example": "python:3.12-slim"
                },
                "limits": {
                    "$ref": "#/definitions/config.ResourceLimits"
                }
            }
        },
        "api.RunResponse": {
            "type": "object",
            "properties": {
                "exit_code": {
                    "type": "integer",
                    "example": 0
                },
                "stderr": {
                    "type": "string",
                    "example": ""
                },
                "stdout": {
                    "type": "string",
                    "example": "hello world\n"
                },
                "wall_ms": {
                    "type": "integer",
                    "example": 342
                }
            }
        },
        "config.ResourceLimits": {
            "type": "object",
            "properties": {
                "cpu_cores": {
                    "type": "number"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "nofile": {
                    "type": "integer"
                },
                "pids_limit": {
                    "type": "integer"
                },
                "wall_clock_secs": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Boxer API",
	Description:      "Sandbox execution service: pull any container image, run arbitrary commands inside gVisor.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
